### ISSUE TITLE
Edit pages getting error messages

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#186]
When I've gone to the edit charity page I have quite often received an error message -- they generally look something like the example below.

There will be a do-a-thon on Saturday week (Sat 16th June) which will be a joint event and looks likely to be well-attended, so it would be good to be confident that these sorts of issues are sorted before then.

![image](https://user-images.githubusercontent.com/18592601/41052995-57f42718-69b2-11e8-9a4b-16604d46ed51.png)

https://app.sogive.org/#edit?charityId=marie-curie-formerly-marie-curie-cancer-care

There was an Error :'(
Try navigating to a different tab, or reloading the page. If this problem persists, please contact support.

assert-failed: "EditCharityPage.ProjectInputEditor"
Error: assert-failed: "EditCharityPage.ProjectInputEditor" at Object.SJTest.assertFailed (https://app.sogive.org/build/js/bundle.js:1035:8) at SJTest.assert (https://app.sogive.org/build/js/bundle.js:1024:9) at ProjectInputEditor (https://app.sogive.org/build/js/bundle.js:105103:21) at mountIndeterminateComponent (https://app.sogive.org/build/js/bundle.js:73832:13) at beginWork (https://app.sogive.org/build/js/bundle.js:74271:14) at performUnitOfWork (https://app.sogive.org/build/js/bundle.js:76301:12) at workLoop (https://app.sogive.org/build/js/bundle.js:76340:24) at renderRoot (https://app.sogive.org/build/js/bundle.js:76380:7) at performWorkOnRoot (https://app.sogive.org/build/js/bundle.js:76997:22) at performWork (https://app.sogive.org/build/js/bundle.js:76918:7)

**Comment by SanjayLikesCharities** [comment]
I have discovered that this can arise not just with edit charity pages, but also edit fundraiser pages too:
https://app.sogive.org/#editFundraiser/sanjay.2pLV4wR7.d3b33f
![image](https://user-images.githubusercontent.com/18592601/41095570-ae849bf2-6a49-11e8-90ca-bcf7ec51201e.png)

There was an Error :'(
Try navigating to a different tab, or reloading the page. If this problem persists, please contact support.

Cannot read property 'sanjay.2pLV4wR7.d3b33f' of undefined
TypeError: Cannot read property 'sanjay.2pLV4wR7.d3b33f' of undefined at Store.getData (https://app.sogive.org/build/js/bundle.js:2402:39) at Misc.SavePublishDiscard (https://app.sogive.org/build/js/bundle.js:22214:33) at mountIndeterminateComponent (https://app.sogive.org/build/js/bundle.js:73832:13) at beginWork (https://app.sogive.org/build/js/bundle.js:74271:14) at performUnitOfWork (https://app.sogive.org/build/js/bundle.js:76301:12) at workLoop (https://app.sogive.org/build/js/bundle.js:76340:24) at renderRoot (https://app.sogive.org/build/js/bundle.js:76380:7) at performWorkOnRoot (https://app.sogive.org/build/js/bundle.js:76997:22) at performWork (https://app.sogive.org/build/js/bundle.js:76918:7) at performSyncWork (https://app.sogive.org/build/js/bundle.js:76890:3)
